投稿表示と簡易ページネーション
fami-gb/simple-post-app pull request #12
Opened 2024-07-05 07:06 UTC by fami-gb

空データへのアクセス処理は後々考えることにしました。
今は取り敢えず、次へ・前へボタンのみでページネーションを実装しています。

2024-07-05 18:31 UTC, yukikamome316 requested changes

2024-07-05 18:31 UTC, yukikamome316 commented on client/script.js
> +const fetchAndDisplayPosts = async (page=1) => {
デフォルト引数指定しなくていいと思う

2024-07-05 18:31 UTC, yukikamome316 commented on client/script.js
> +    (page == 1) ? disabledFlag = true : disabledFlag = false;
```suggestion
    disabledFlag = (page == 1);
```

2024-07-05 18:31 UTC, yukikamome316 commented on client/script.js
> +});
存在しないpageに対してもfetchを要求することにならない？
`currentPage` が1のときにデクリメントして、`page=0`になるなど

2024-07-05 18:33 UTC, yukikamome316 commented
全ファイルに共通したことだけど、最終行で空の改行を入れよう

2024-07-05 18:34 UTC, yukikamome316 requested changes
とりあえずフォーマットして欲しい

2024-07-05 18:34 UTC, yukikamome316 commented on client/script.js
> +    if (Object.keys(postList).length  === 0) {
```suggestion
    if (Object.keys(postList).length === 0) {
```

2024-07-05 19:04 UTC, fami-gb commented on client/script.js
> +});
`currentPage=1`のときに「前へ」ボタンを無効にすることで(`prevBtn.disabled = (page == 1)`)そもそもデクリメントさせないようにしています。

2024-07-05 19:11 UTC, fami-gb commented on client/script.js
> +});
ただし現状、データ数が2ページ分しかないのに3ページ目を表示できてしまうのが問題です。その際の処理は現在思案中です。

2024-07-07 16:10 UTC, yukikamome316 approved these changes

2024-07-07 16:10 UTC, merged