投稿機能の追加
fami-gb/simple-post-app pull request #13
Opened 2024-07-07 17:08 UTC by fami-gb

投稿機能を追加しました。

プルリクのタイミングがよく分からなかったので取り敢えず早めに出すようにしました。(進捗状況もつかみやすいと思うので)

2024-07-11 08:19 UTC, yukikamome316 requested changes

2024-07-11 08:19 UTC, yukikamome316 commented on client/index.html
> +            <input type="text" id="qbox" placeholder="質問を入力して下さい。">
client側で `required` 指定しないと空の質問を投稿できてしまう

2024-07-11 08:19 UTC, yukikamome316 commented on client/script.js
> +        body: JSON.stringify({"question": qText.value}),
qTextは本当にtruthyか？

https://typescriptbook.jp/reference/values-types-variables/truthy-falsy-values

2024-07-11 08:23 UTC, yukikamome316 commented on client/script.js
> +        body: JSON.stringify({"question": qText.value}),
P.S. `qText` という変数名を見ると String であることを連想してしまうから、`qTextElememt` などに変更しよう

2024-07-11 08:25 UTC, yukikamome316 requested changes

2024-07-11 08:25 UTC, yukikamome316 commented on client/index.html
> +        <div id="posting">
ここに `id` つける必要ある？

2024-07-11 08:25 UTC, yukikamome316 commented on client/script.js
>  const nextBtn = document.getElementById("next");
Elementの件と同様

2024-07-11 16:33 UTC, fami-gb commented on client/index.html
> +        <div id="posting">
後にcssで装飾をする際に、投稿部分とそれ以外で分けて装飾したいと考えているのでid付けておきました。

2024-07-12 07:01 UTC, yukikamome316 commented on client/index.html
> +        <div id="posting">
CSSでスタイル適応するなら `id` じゃなくて `class` 使おう
それに今は参照されてないから消した方が保守の観点から良い

2024-07-12 07:03 UTC, yukikamome316 requested changes

2024-07-12 07:03 UTC, yukikamome316 commented on client/script.js
> +        body: JSON.stringify({"question": qTextElement.value}),
クライアント側で `required` したから不正な入力は確かに防げているが、サーバー側でもチェックするのが定石
ダブルチェックするように変更しよう！

2024-07-12 10:03 UTC, fami-gb commented on client/index.html
> +        <div id="posting">
了解です。

2024-07-12 11:44 UTC, yukikamome316 approved these changes

2024-07-12 11:44 UTC, merged