投稿件数の取得
fami-gb/simple-post-app pull request #15
Opened 2024-07-14 11:32 UTC by fami-gb

グローバル変数である`postData`を用いてデータ数を取得したが、`http://localhost:8000/api/posts`から取得したほうがいいのか疑問。

2024-07-15 04:10 UTC, yukikamome316 requested changes

2024-07-15 04:10 UTC, yukikamome316 commented on server/server.js
> +  const postCounter = Object.keys(postsData).length;
`postsCount` かな

2024-07-15 04:10 UTC, yukikamome316 commented on server/server.js
> +  const postCounter = Object.keys(postsData).length;
普通に `postsData.length` じゃだめだっけ？

2024-07-15 05:38 UTC, fami-gb commented on server/server.js
> +  const postCounter = Object.keys(postsData).length;
行けますね。。

2024-07-15 13:32 UTC, yukikamome316 commented
変数名の変更はリファクタリングに分類されると思う

2024-07-15 13:57 UTC, fami-gb commented
わ、ほんとですね。
家帰ったら頑張ってみます

2024-07-31 02:56 UTC, yukikamome316 approved these changes

2024-07-31 02:58 UTC, yukikamome316 requested changes
失礼、これだけ

2024-07-31 02:58 UTC, yukikamome316 commented on server/server.js
> +  return c.json(splitedPosts, 200)
```suggestion
  return c.json(splitedPosts, 200);
```

2024-07-31 02:58 UTC, yukikamome316 commented on server/server.js
>      return err.getResponse()
```suggestion
    return err.getResponse();
```

2024-08-08 16:02 UTC, fami-gb commented
マージお願いします！！

2024-08-09 04:10 UTC, merged